### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Ultranmus** [crasowas/app_store_required_privacy_manifest_analyser#1]
Can it be used in window(non apple device)?
I tried running on cmd in windows laptop so it was  giving this error
`The term 'sh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.`

but after looking into internet i found that i can use this in git bash and then it gives this error
`sh: privacy_manifest_analyser.sh: No such file or directory`

the command i run in git bash was:
` sh privacy_manifest_analyser.sh "C:\my_projects\flutter_projects\test-app\ios"`

I found about **app_store_required_privacy_manifest_analyser** after reading this [comment](https://github.com/flutter/flutter/issues/131940#issuecomment-2039669883) from someone who advised me to use **app_store_required_privacy_manifest_analyser** but i am not sure how to properly use it

**Comment by crasowas** [comment]
@Ultranmus I understand your issue, but unfortunately this script does not work on non-Apple devices.

When scanning the usage of APIs in binary files, the `xcrun swift-demangle` command is needed. However, this command relies on the `Xcode Command Line Tools` environment, which appears to be unavailable on non-Apple devices.

For this reason, non-Apple devices will not be supported for the time being.

**Comment by Ultranmus** [comment]
@crasowas so this will run on Mac, no problem I can try this in Mac. One more thing, can you check if there is no syntax problem with below command? 
```
sh privacy_manifest_analyser.sh "C:\my_projects\flutter_projects\test-app\ios"

**Comment by crasowas** [comment]
There is no problem with the syntax. The error on Windows may be due to a problem with the directory path format.

**Comment by Ultranmus** [comment]
Thanxs man, I'll test it in Mac.
