### ISSUE TITLE
Some explanation regarding the symbols

### ISSUE THREAD

**Issue by aggeloskoutanis** [crasowas/app_store_required_privacy_manifest_analyser#13]
Hello, thanks a lot for creating this tool. It is so helpful. I have some follow-up questions.

1. Should I include a privacy manifest file for my app, even though I have nothing to declare inside it?
2. Regarding your tool. After the run is completed, I get to see an overview of the run with some emojis. Like the following:

==================== Analysis completed! ⏰: 1684s 💡: 38 ⚠️ : 68 🛠️ : 12 ✅: 37 🎯: 35 ====================   

How does this overview look for an app with no privacy problems when submitted to the Apple Store?

3. Some 3rd party SDKs return this 
```
Analyzing firebase_performance-0.9.4+3 ...
⚠️  Missing privacy manifest file!
API usage analysis result(s): 0
```

Since they have API usage analysis result(s): **0**, should they include a privacy manifest nevertheless?

**Comment by crasowas** [comment]
1. As far as I know, it's best to create a privacy manifest for your app. Here are two key reasons:
    * The privacy manifest not only declares which APIs your app uses but also describes the data the app collects and why. This information is essential for generating a privacy report to help you complete Privacy Nutrition Labels. However, currently, this doesn't seem to affect the App Store review.
    * Despite many statically linked libraries having their own privacy manifest, they could still affect your app's privacy manifest. It's highly recommended to analyze your application bundle (`.app`) before submitting it for App Store review.
2. Regarding the processing needed for these emojis, you can refer to the [README](https://github.com/crasowas/app_store_required_privacy_manifest_analyser/blob/main/README.md#1-getting-started).
3. If it's not one of the commonly used SDKs tagged with `🎯`, it seems unnecessary for now, but it may be needed in the future.

I hope the above information is useful to you. :)

**Comment by aggeloskoutanis** [comment]
Thanks. Much appreciated!
