### ISSUE TITLE
Package Dependencies using Swift Package Manager

### ISSUE THREAD

**Issue by socialvanana** [crasowas/app_store_required_privacy_manifest_analyser#15]
It looks like not all dependencies are inpected.

How to inspect 3rd party libraries implemented by Swift Package Manager?

**Comment by crasowas** [comment]
The feature is now available! Feel free to reanalyze your project. 

Here's an example for reference: [ios_swiftpm_example](https://github.com/crasowas/app_store_required_privacy_manifest_analyser/tree/main/Examples/ios_swiftpm_example).
