### ISSUE TITLE
运行Example失败

### ISSUE THREAD

**Issue by zhllineme** [crasowas/app_store_required_privacy_manifest_analyser#17]
设备 mac mini M2
系统：macOS Sequoia 15.0 
Xcode 16.0

xxx@xxxdeMac-mini ~ % xcrun swift -version
swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0

报错：

xxx@xxxMac-mini app_store_required_privacy_manifest_analyser % sh privacy_manifest_analyser.sh ./Examples/ios_example 
: command not foundalyser.sh: line 2: 
: command not foundalyser.sh: line 8: 
: command not foundalyser.sh: line 11: 
: command not foundalyser.sh: line 14: 
: command not foundalyser.sh: line 17: 
: command not foundalyser.sh: line 20: 
: command not foundalyser.sh: line 23: 
'rivacy_manifest_analyser.sh: line 26: syntax error near unexpected token `in
'rivacy_manifest_analyser.sh: line 26: `  case $opt in

**Comment by crasowas** [comment]
Is this the full error log?
I'm kind of confused about `foundalyser.sh`, what is it?

**Comment by crasowas** [comment]
It seems like the errors are coming from blank lines. Try running `cat -v privacy_manifest_analyser.sh` to see if there are any special line breaks.

**Comment by zhllineme** [comment]
cat -v privacy_manifest_analyser.sh checks that there are indeed special characters. 
The reason is that I copy the windows project from github to mac, resulting in some windows characters in the sh file
